@HeThongThiBangLai.Api_HostAddress = http://localhost:5017

GET {{HeThongThiBangLai.Api_HostAddress}}/weatherforecast/
Accept: application/json

### Login with admin
POST {{HeThongThiBangLai.Api_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "ten_dang_nhap_hoac_email": "admin",
  "mat_khau": "Admin@123"
}

###
